// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: playlist.proto

package mapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MusicServiceClient is the client API for MusicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MusicServiceClient interface {
	// Play will start to play music in queue
	PlaySong(ctx context.Context, in *PlaySongRequest, opts ...grpc.CallOption) (*PlaySongResponse, error)
	// Pause will stop playing current song
	PauseSong(ctx context.Context, in *PauseSongRequest, opts ...grpc.CallOption) (*PauseSongResponse, error)
	// AddSong will add a new song to the end of queue
	AddSong(ctx context.Context, in *AddSongRequest, opts ...grpc.CallOption) (*AddSongResponse, error)
	// Next will skip current song
	NextSong(ctx context.Context, in *NextSongRequest, opts ...grpc.CallOption) (*NextSongResponse, error)
	// PrevSong will turn previous song
	PrevSong(ctx context.Context, in *PrevSongRequest, opts ...grpc.CallOption) (*PrevSongResponse, error)
}

type musicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMusicServiceClient(cc grpc.ClientConnInterface) MusicServiceClient {
	return &musicServiceClient{cc}
}

func (c *musicServiceClient) PlaySong(ctx context.Context, in *PlaySongRequest, opts ...grpc.CallOption) (*PlaySongResponse, error) {
	out := new(PlaySongResponse)
	err := c.cc.Invoke(ctx, "/MusicService/PlaySong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) PauseSong(ctx context.Context, in *PauseSongRequest, opts ...grpc.CallOption) (*PauseSongResponse, error) {
	out := new(PauseSongResponse)
	err := c.cc.Invoke(ctx, "/MusicService/PauseSong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) AddSong(ctx context.Context, in *AddSongRequest, opts ...grpc.CallOption) (*AddSongResponse, error) {
	out := new(AddSongResponse)
	err := c.cc.Invoke(ctx, "/MusicService/AddSong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) NextSong(ctx context.Context, in *NextSongRequest, opts ...grpc.CallOption) (*NextSongResponse, error) {
	out := new(NextSongResponse)
	err := c.cc.Invoke(ctx, "/MusicService/NextSong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicServiceClient) PrevSong(ctx context.Context, in *PrevSongRequest, opts ...grpc.CallOption) (*PrevSongResponse, error) {
	out := new(PrevSongResponse)
	err := c.cc.Invoke(ctx, "/MusicService/PrevSong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MusicServiceServer is the server API for MusicService service.
// All implementations must embed UnimplementedMusicServiceServer
// for forward compatibility
type MusicServiceServer interface {
	// Play will start to play music in queue
	PlaySong(context.Context, *PlaySongRequest) (*PlaySongResponse, error)
	// Pause will stop playing current song
	PauseSong(context.Context, *PauseSongRequest) (*PauseSongResponse, error)
	// AddSong will add a new song to the end of queue
	AddSong(context.Context, *AddSongRequest) (*AddSongResponse, error)
	// Next will skip current song
	NextSong(context.Context, *NextSongRequest) (*NextSongResponse, error)
	// PrevSong will turn previous song
	PrevSong(context.Context, *PrevSongRequest) (*PrevSongResponse, error)
	mustEmbedUnimplementedMusicServiceServer()
}

// UnimplementedMusicServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMusicServiceServer struct {
}

func (UnimplementedMusicServiceServer) PlaySong(context.Context, *PlaySongRequest) (*PlaySongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaySong not implemented")
}
func (UnimplementedMusicServiceServer) PauseSong(context.Context, *PauseSongRequest) (*PauseSongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseSong not implemented")
}
func (UnimplementedMusicServiceServer) AddSong(context.Context, *AddSongRequest) (*AddSongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSong not implemented")
}
func (UnimplementedMusicServiceServer) NextSong(context.Context, *NextSongRequest) (*NextSongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextSong not implemented")
}
func (UnimplementedMusicServiceServer) PrevSong(context.Context, *PrevSongRequest) (*PrevSongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrevSong not implemented")
}
func (UnimplementedMusicServiceServer) mustEmbedUnimplementedMusicServiceServer() {}

// UnsafeMusicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MusicServiceServer will
// result in compilation errors.
type UnsafeMusicServiceServer interface {
	mustEmbedUnimplementedMusicServiceServer()
}

func RegisterMusicServiceServer(s grpc.ServiceRegistrar, srv MusicServiceServer) {
	s.RegisterService(&MusicService_ServiceDesc, srv)
}

func _MusicService_PlaySong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaySongRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).PlaySong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MusicService/PlaySong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).PlaySong(ctx, req.(*PlaySongRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_PauseSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseSongRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).PauseSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MusicService/PauseSong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).PauseSong(ctx, req.(*PauseSongRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_AddSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSongRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).AddSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MusicService/AddSong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).AddSong(ctx, req.(*AddSongRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_NextSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextSongRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).NextSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MusicService/NextSong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).NextSong(ctx, req.(*NextSongRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicService_PrevSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrevSongRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicServiceServer).PrevSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MusicService/PrevSong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicServiceServer).PrevSong(ctx, req.(*PrevSongRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MusicService_ServiceDesc is the grpc.ServiceDesc for MusicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MusicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MusicService",
	HandlerType: (*MusicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaySong",
			Handler:    _MusicService_PlaySong_Handler,
		},
		{
			MethodName: "PauseSong",
			Handler:    _MusicService_PauseSong_Handler,
		},
		{
			MethodName: "AddSong",
			Handler:    _MusicService_AddSong_Handler,
		},
		{
			MethodName: "NextSong",
			Handler:    _MusicService_NextSong_Handler,
		},
		{
			MethodName: "PrevSong",
			Handler:    _MusicService_PrevSong_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "playlist.proto",
}
